### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by atanaschristov** [Bustanity/cordova-plugin-audiofocus#1]
It seems that since cordova 7.0.0 package.json is required for the npm to work properly. 

Check this out: https://github.com/ionic-team/cordova-plugin-ios-keychain/issues/21

**Comment by davidhyl** [comment]
having the same issue here. Can it be added or I can do a PR to have someone merge the changes in? Thanks

**Comment by teemupynnonen** [comment]
Thank you for reporting this issue, although bit late, it has now been fixed with commit b3963be
